# Generated by Django 3.2.4 on 2024-02-05 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('host', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tos', models.IntegerField(default=0)),
                ('add_dt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackedhost')),
            ],
        ),
    ]
